### 20장. 뒷정리하기 
### **나중에 tearDown 호출하기**
- 테스트가 서로 독립적이길 바란다면 외부 자원을 할당받은 테스트들은 작업을 마치기 전에 tearDown() 메서드 같은 곳에서 자원을 다시 반환할 필요가 있다. 
- 할당 해제를 위한 테스트 방법은 또 하나의 플래그를 도입하는 것이다. 
- 하지만 플래그를 사용하는 방식은 메서드의 중요한 면을 하나 놓치고 있다. 
- 바로 setUp()은 테스트 메서드가 실행되기 전에 호출되어야하고 tearDown()은 테스트메서드가 실행된 후에 호출되어야한다는 점이다. 

-> 로그를 남기는 식으로 테스트 전략을 바꾼다. 

### **WasRun에 로그 문자열 남기기**
```python
# WasRun.py
def setUp(self):
    self.wasRun = None
    self.wasSetUp = 1
    self.log = "setUp "

# 이제 testSetUp()이 플래그 대신 로그를 검사하도록 변경할 수 있다. 
# TestCaseTest.py
def testSetUp(self):
    self.test.run()
    assert("setUp " == self.test.log)
```
- 이제 wasSetUp 플래그르 지울 수 있다. 
- 후에 테스트 메서드의 실행을 기록할 수 있다. 
```python
# WasRun.py
def testMethod(self):
    self.wasRun = 1
    self.log = self.log + "testMethod "
```
- testSetUp을 실패하게 만든다. 예상되는 값을 바꾸자.
```python
def testSetUp(self):
    self.test.run()
    assert("setUp testMethod " == self.test.log)
```
- 이제 이테스트는 두 개의 테스트가 할 일을 모두 수행한다. 
- 따라서 test-Running을 지우고 testSetUp의 이름을 바꿔주자. 

```python
# TestCaseTest.py
def setUp(self):
    self.test = WasRun("testMethod")
def testTemplateMethod(self):
    self.test.run()
    assert("setUp testMethod " == self.test.log)
```
- WasRun의 인스턴스를 한곳에서만 사용하므로 꾀를 써서 setUp 부분을 분리했던 것을 되돌려 놓아야한다. 
```python
def testTemplateMethod(self):
    test = WasRun("testMethod")
    test.run()
    assert("setUp testMethod " == self.test.log)
```
- 앞에서 두번 사용한 것으로 인해 리팩토링했다가 이를 다시 되돌리는 일은 자주 있는 일이다. 

### **나중에 tearDown 호출하기**
- 이제 tearDown을 테스트할 준비가 되었다. 
```python
# TestCaseTest.py
def testTemplateMethod(self):
    test = WasRun("testMethod")
    test.run()
    assert("setUp testMethod tearDown " == test.log)
```

- 실패하지만 성공하도록 만들 수 있다. 
```python
# TestCase.py
def run(self):
    self.setUp()
    method = getattr(self. self.name)
    method()
    self.tearDown()

# WasRun.py
def setUp(self):
    self.log = "setUp "
def testMethod(self):
    self.log += "testMethod "

def tearDown(self):
    self.log += "tear Down "
```
- 이제 WasRun이 아니라 TestCaseTest에서 에러가 난다. 
- 아직 TestCase에 tearDown()을 구현하지 않았다. 
```python
# TestCase.py
def tearDown(self):
    pass
```
- 이럴 경우 리팩토링이 필요없다. 
- 사소한 문제가 발생한 후에 있었던 명백한 구현은 제대로 작동했고 또 깨끗했다. 

### 지금까지 한 작업 검토
1. 플래그에서 로그로 테스트 전략을 구조 조정했다. 
2. 새로운 로그 기능을 이용하여 tearDown()을 테스트하고 구현했다. 
3. 문제를 발견했는데 뒤로 되돌아가는 대신 과감히 수정했다.
